services:
  web:
    build:
      context: /home/linas/portfolio/docker/caronte/
      dockerfile: ./dockerfiles/base/ubbase 
     # args: #Variables de DFILE para la construcci√≥n de las imagenes 
     #   - USUARIO=linas
    container_name: ${CONTAINER_NAME}
    # environment:
    #   - USUARIO=linas
    #   - PASSWORD=1234
    ports:
      - ${PORT_SSH}:${PORT_SSH}
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs