services:
  web:
    build:
      context: /home/linas/portfolio/Docker/caronte/
      dockerfile: ./dockerfiles/sweb/ngnix/Dockerfile 
     # args: #Variables de DFILE para la construcci√≥n de las imagenes 
     #   - USUARIO=linas
    container_name: ${CONTAINER_NAME}
    # environment:
    #   - USUARIO=linas
    #   - PASSWORD=1234
    image: linas/swebngnix
    ports:
      - ${PORT_SSH}:${PORT_SSH}
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      netcaronte:
        ipv4_address: ${IP}
networks:
  netcaronte:
    external: true